import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Mind Mate Color System (from new.html) ──
        'secondary-container': '#dfe3e8',
        'on-background': '#1b1c1d',
        'on-surface': '#1b1c1d',
        'on-surface-variant': '#434653',
        outline: '#737784',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#42474b',
        secondary: '#5a5f63',
        'on-primary-fixed': '#001946',
        background: '#faf9fa',
        'on-error-container': '#93000a',
        'inverse-primary': '#b1c5ff',
        'surface-container-low': '#f5f3f4',
        'on-tertiary-fixed-variant': '#524600',
        'secondary-fixed-dim': '#c2c7cc',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#3366cc',
        'tertiary-fixed': '#f9e37a',
        'outline-variant': '#c3c6d5',
        'surface-dim': '#dbdadb',
        'primary-fixed-dim': '#b1c5ff',
        tertiary: '#6d5e00',
        'surface-container-high': '#e9e8e9',
        'inverse-on-surface': '#f2f0f1',
        'on-secondary-fixed': '#171c20',
        'surface-bright': '#faf9fa',
        'primary-fixed': '#d9e2ff',
        'on-primary-container': '#e7ebff',
        'on-tertiary-container': '#4a3f00',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#211b00',
        'error': '#ba1a1a',
        'on-secondary-container': '#606569',
        'surface-container-highest': '#e3e2e3',
        'on-error': '#ffffff',
        'surface-container': '#efedee',
        'surface-variant': '#e3e2e3',
        surface: '#faf9fa',
        'inverse-surface': '#303031',
        'tertiary-fixed-dim': '#dcc661',
        'tertiary-container': '#bfab49',
        primary: '#094cb2',
        'secondary-fixed': '#dfe3e8',
        'on-primary-fixed-variant': '#00419d',
        'surface-tint': '#2259bf',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
      },
      fontFamily: {
        headline: ['var(--font-noto-serif)', 'serif'],
        display: ['var(--font-noto-serif)', 'serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-public-sans)', 'sans-serif'],
        'label-sm': ['var(--font-public-sans)', 'sans-serif'],
        'headline-lg': ['var(--font-noto-serif)', 'serif'],
        'headline-md': ['var(--font-noto-serif)', 'serif'],
        'headline-sm': ['var(--font-noto-serif)', 'serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'sans-serif'],
        'label-md': ['var(--font-public-sans)', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        'container-max-width': '1200px',
        'chat-width': '768px',
      },
      maxWidth: {
        'chat-width': '768px',
      },
    },
  },
  plugins: [],
}

export default config
